version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-password
      POSTGRES_DB: dsb_news_development
    volumes:
      - "db_data:/var/lib/postgresql/data"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-password
      POSTGRES_DB: dsb_news_development
    volumes:
      - .:/app

volumes:
  db_data:
